package:
  name: typedunits
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/TypedUnits.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps  --no-build-isolation
  number: 0

channels:
  - conda-forge
  - martinpdes

requirements:
  host:
    - python {{ PY_VER }}*
    - setuptools >=40.8.0
    - wheel
    - setuptools-scm >=8.0
    - pip
  run:
    - pint
    - numpy


about:
  home: https://github.com/MartinPdeS/TypedUnits
  license: MIT
  summary: "A package wrapping pint for handling typed units in Python."
  description: TypedUnits is a library that provides a way to define and manipulate physical quantities with units in a type-safe manner. It builds on top of the Pint library.
  dev_url: https://github.com/MartinPdeS/TypedUnits
  doc_url: https://typedunits.readthedocs.io
  license_file: LICENSE
  keywords:
    - typed units
    - pint
    - physical quantities

test:
  imports:
    - TypedUnits
  requires:
    - python {{PY_VER}}*
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ~=1.5.0
    - coverage ~=7.6.1
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS