name: Publish documentation

on:
  push:
    branches: [master]
    tags: ["v*"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  documentation:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_documentation.yml@v5
    with:
      python-version: "3.11"
      package-name: TypedUnit
      apt-package: xvfb jq
